__include__: [
  './rtdetr_r50vd_6x_neudet.yml',
]

PResNet:
  return_idx:
  - 0
  - 1
  - 2
  - 3

BaselineHybridEncoder:
  use_s2_enhance: true
  use_s2_attn_gated: false
  use_s2_cross_attn: true
  s2_in_channels: 64
