use_ema: True
ema:
  type: ModelEMA
  decay: 0.9999
  warmups: 2000

find_unused_parameters: True

epoches: 72
clip_max_norm: 0.1

optimizer:
  type: AdamW
  params:
    -
      params: 'backbone'
      lr: 0.000005         # 预训练 backbone 保持较小学习率
    -
      params: '^(?=.*encoder(?=.*bias|.*norm.*weight)).*$'
      weight_decay: 0.
    -
      params: '^(?=.*decoder(?=.*bias|.*norm.*weight)).*$'
      weight_decay: 0.

  lr: 0.000085             # bs=8 (8.5e-5)
  betas: [0.9, 0.999]
  weight_decay: 0.0001

lr_scheduler:
  type: MultiStepLR
  milestones: [54, 66]     # 72 epochs 下在后 25% 与后 10% 两次衰减
  gamma: 0.1
