sync_bn: True
find_unused_parameters: False


use_amp: True

scaler:
  type: GradScaler
  enabled: True


use_ema: False
ema:
  type: ModelEMA
  decay: 0.9999
  warmups: 2000

early_stopping:
  enabled: False
  monitor: mAP_50:95
  mode: max
  patience: 10
  min_delta: 0.0
  start_epoch: 10
